# Task 4
Name: Tanushree Sharma

REG No.: GO_STP_928

In [19]:
import numpy as np
print(np.__version__)
print(np.show_config)

1.19.2
<function show at 0x00727F10>


In [15]:
null_vactor = np.zeros(10)
print(null_vactor)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
array = np.array([10,38,85,57,78,97,32,35,11,65])
print(array.dtype)

int32


In [17]:
array.ndim

1

In [20]:
array.itemsize


4

In [19]:
array.nbytes

40

In [23]:
vector = np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [24]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [31]:
print(np.flip(vector))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [41]:
matrix= np.arange(0,9)
matrix.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
array = [1,2,0,0,4,0]
np.nonzero(array)

(array([0, 1, 4], dtype=int32),)

In [45]:
matrix = np.identity(3)
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.random.random((3,3,3))

array([[[0.61762914, 0.13948286, 0.53484255],
        [0.20832702, 0.0245882 , 0.70709484],
        [0.90663592, 0.31157318, 0.36336523]],

       [[0.29892826, 0.25892615, 0.01294021],
        [0.65216354, 0.42923685, 0.33067948],
        [0.6964044 , 0.14982562, 0.04227559]],

       [[0.97422806, 0.94470636, 0.76425598],
        [0.81424339, 0.07598739, 0.60093066],
        [0.51947154, 0.47103567, 0.1490211 ]]])

In [50]:
matrix= np.random.random((10,10))
print(matrix)
print("Minimum Value :", matrix.min())
print("Maximum Value :", matrix.max())

[[0.80276289 0.1396621  0.57762504 0.49712558 0.96797441 0.81072944
  0.87089516 0.87837694 0.44713819 0.49971629]
 [0.2063998  0.80273208 0.80819094 0.28259666 0.10268051 0.93635287
  0.43757149 0.85845577 0.36162586 0.08233929]
 [0.77144401 0.13640361 0.76233884 0.842254   0.83844916 0.39200411
  0.91905533 0.10318262 0.34011369 0.20743968]
 [0.91082157 0.11815553 0.73068939 0.21051604 0.84094511 0.11222756
  0.82399537 0.63959272 0.88367569 0.25674931]
 [0.49980246 0.19816336 0.29262195 0.91690084 0.41926199 0.92641449
  0.83445705 0.60960202 0.23128995 0.05496666]
 [0.40771463 0.03484965 0.46867564 0.88684315 0.70720773 0.82249389
  0.12031343 0.30860732 0.17966833 0.91357063]
 [0.00723902 0.50117092 0.18605393 0.12609108 0.12725133 0.00659004
  0.31905557 0.83636421 0.64237365 0.24021688]
 [0.74047125 0.81265904 0.39321804 0.59787834 0.9528257  0.57016518
  0.60518524 0.90801767 0.55813414 0.48669368]
 [0.71642974 0.35440575 0.41251192 0.47635483 0.79913738 0.86046669
  0.61922952

In [53]:
vector = np.random.random((30))
print("Vector: ",vector)
print("Mean: ",vector.mean())

Vector:  [0.5686658  0.39749881 0.70424304 0.41773867 0.04175239 0.26585732
 0.23129613 0.08597118 0.62269171 0.9074327  0.61768549 0.30267286
 0.706822   0.92819906 0.12141947 0.5314026  0.10302925 0.50377062
 0.79115225 0.9547506  0.24546572 0.19416204 0.34367437 0.01938066
 0.38415    0.88985803 0.61075293 0.04305856 0.23541746 0.68623269]
Mean:  0.44854014691120764


In [57]:
array = np.ones((4,4))
array[1:3,1:3]=0
print(array)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [60]:
array = np.zeros((4,4))
array[1:3,1:3]=1
print(array)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [70]:
array = np.array([[ 1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("Accessing Element 13 : ", array[1,5])
print("First Row : ", array[0])
print("Third column : ", array[0,2])
print(array[0,1:6:2])
array[1,5] = 20
print("Replace Element 13 : ", array[1,5])

Accessing Element 13 :  13
First Row :  [1 2 3 4 5 6 7]
Third column :  3
[2 4 6]
Replace Element 13 :  20


In [71]:
randomarr = np.random.random(10)
randomarr = randomarr.reshape(2,5)
randomarr

array([[0.58471509, 0.86493963, 0.17815161, 0.51075522, 0.19123215],
       [0.4532872 , 0.83567696, 0.98742277, 0.39310609, 0.10735054]])

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
a = np.append(np.repeat(a,3),np.tile(a,3))
print(a)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [42]:
l = range(1000)
import sys
a = 10
print("Size of list : ", sys.getsizeof(a)*len(l))
a1 = np.arange(1000)
print("Size of numpy array : ", a1.size*a1.itemsize)

Size of list :  14000
Size of numpy array :  4000


In [43]:
import time
import sys
size =1000000
l1 = range(size)
l2 = range(size)
n1 = np.arange(size)
n2 = np.arange(size)
start = time.time( )
res = [(x+y) for x,y in zip(l1,l2)]
print("Time take by List : ", (time.time()-start)*1000)
start = time.time( )
res1 = n1+n2
print("Time taken by numpy array : ", (time.time()-start)*1000)

Time take by List :  157.70554542541504
Time taken by numpy array :  15.622377395629883
